package com.volunteerhub.notificationservice.model;

public enum NotificationType {
    EVENT_REQUESTED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    EVENT_DELETED,
    EVENT_UPDATED,
    USER_EVENT_REQUESTED,
    USER_EVENT_APPROVED,
    USER_EVENT_REJECTED,
    USER_EVENT_COMPLETED,
    POST_CREATED,
    POST_UPDATED,
    REACTION_CREATED,
    COMMENT_CREATED,
    REACTION,
    COMMENT,
    CHAT_MESSAGE,
    USER_ACTIVE,
    USER_BANNED
}
