apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: service-discovery
    patch: &spring-startup-probe |-
      - op: add
        path: /spec/progressDeadlineSeconds
        value: 1800
      - op: add
        path: /spec/strategy
        value:
          type: Recreate
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          tcpSocket:
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 120
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
  - target:
      kind: Deployment
      name: api-gateway
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: authorization-server
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: user-service
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: event-service
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: community-service
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: registration-service
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: notification-service
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: aggregation-service
    patch: *spring-startup-probe
  - target:
      kind: Deployment
      name: analytic-service
    patch: *spring-startup-probe
  - target:
      kind: StatefulSet
      name: rabbitmq
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
