--
-- PostgreSQL database dump
--

\restrict kdAzY8yCand9f9ROhpEAa8ohVQqUnJo7DEtCLxy80U8ipwusSjyEsNUkFAqy5M5

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: notification; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    actor_id character varying(255) NOT NULL,
    context_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    payload jsonb,
    type character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['EVENT_REQUESTED'::character varying, 'EVENT_APPROVED'::character varying, 'EVENT_REJECTED'::character varying, 'EVENT_DELETED'::character varying, 'EVENT_UPDATED'::character varying, 'USER_EVENT_REQUESTED'::character varying, 'USER_EVENT_APPROVED'::character varying, 'USER_EVENT_REJECTED'::character varying, 'USER_EVENT_COMPLETED'::character varying, 'POST_CREATED'::character varying, 'POST_UPDATED'::character varying, 'REACTION'::character varying, 'COMMENT'::character varying, 'USER_ACTIVE'::character varying, 'USER_BANNED'::character varying])::text[])))
);


ALTER TABLE public.notification OWNER TO admin;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    endpoint character varying(2048) NOT NULL,
    auth character varying(255),
    p256dh character varying(255),
    user_id character varying(255)
);


ALTER TABLE public.subscriptions OWNER TO admin;

--
-- Name: subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.notification (id, actor_id, context_id, created_at, is_read, payload, type, user_id) FROM stdin;
1	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 21:33:13.996864	f	{"updated_fields": {"name": "Bãi biển", "address": "S205, Vinhomes Smart City, Quan Hoa, Hà Nội", "capacity": 10, "category": "environment", "end_time": [2025, 12, 27, 18, 16], "start_time": [2025, 12, 7, 18, 11], "description": "Tuyệt vời", "registration_deadline": [2025, 12, 11, 18, 11]}}	EVENT_UPDATED	3c7fc337-528c-478a-8fb8-53cbbc266725
2	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 21:33:14.091393	f	{"updated_fields": {"name": "Bãi biển", "address": "S205, Vinhomes Smart City, Quan Hoa, Hà Nội", "capacity": 10, "category": "environment", "end_time": [2025, 12, 27, 18, 16], "start_time": [2025, 12, 7, 18, 11], "description": "Tuyệt vời", "registration_deadline": [2025, 12, 11, 18, 11]}}	EVENT_UPDATED	ef87abed-f4ad-4647-8c95-e4f34f34dbba
3	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 21:33:14.098042	f	{"updated_fields": {"name": "Bãi biển", "address": "S205, Vinhomes Smart City, Quan Hoa, Hà Nội", "capacity": 10, "category": "environment", "end_time": [2025, 12, 27, 18, 16], "start_time": [2025, 12, 7, 18, 11], "description": "Tuyệt vời", "registration_deadline": [2025, 12, 11, 18, 11]}}	EVENT_UPDATED	115404184867109357292
4	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 21:33:14.104381	f	{"updated_fields": {"name": "Bãi biển", "address": "S205, Vinhomes Smart City, Quan Hoa, Hà Nội", "capacity": 10, "category": "environment", "end_time": [2025, 12, 27, 18, 16], "start_time": [2025, 12, 7, 18, 11], "description": "Tuyệt vời", "registration_deadline": [2025, 12, 11, 18, 11]}}	EVENT_UPDATED	5fc47331-6243-4997-b08b-d18af4420aa5
5	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 21:33:14.112656	f	{"updated_fields": {"name": "Bãi biển", "address": "S205, Vinhomes Smart City, Quan Hoa, Hà Nội", "capacity": 10, "category": "environment", "end_time": [2025, 12, 27, 18, 16], "start_time": [2025, 12, 7, 18, 11], "description": "Tuyệt vời", "registration_deadline": [2025, 12, 11, 18, 11]}}	EVENT_UPDATED	5f666bb5-ef5b-4123-9c62-b6edc382105c
6	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 21:33:14.120396	f	{"updated_fields": {"name": "Bãi biển", "address": "S205, Vinhomes Smart City, Quan Hoa, Hà Nội", "capacity": 10, "category": "environment", "end_time": [2025, 12, 27, 18, 16], "start_time": [2025, 12, 7, 18, 11], "description": "Tuyệt vời", "registration_deadline": [2025, 12, 11, 18, 11]}}	EVENT_UPDATED	de4050ff-5c12-41a1-bc36-29c06c276ada
7	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	36	2025-12-21 21:33:14.492862	f	{"updated_fields": {"name": "Hiến máu tại Viện Máu TW", "address": "Viện máu, Huyện Bảo Lạc, Tỉnh Cao Bằng", "capacity": 200, "category": "health", "end_time": [2025, 12, 27, 16, 58], "start_time": [2025, 12, 23, 16, 2], "description": "Một sự kiện hữu ích cho mọi người muốn cống hiến vì cộng đồng", "registration_deadline": [2025, 12, 22, 20, 58]}}	EVENT_UPDATED	3c7fc337-528c-478a-8fb8-53cbbc266725
9	372b41ae-9f4e-4abe-b909-07c778f1f84f	43	2025-12-21 22:52:59.847424	f	{"name": "Chiến dịch làm sạch bãi biển mùa hè", "category": "environment", "approved_time": [2025, 12, 21, 22, 52, 57, 722117800]}	EVENT_APPROVED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
10	372b41ae-9f4e-4abe-b909-07c778f1f84f	41	2025-12-21 22:53:05.073587	f	{"name": "Sự kiện nhặt rác ở Quảng Trường Hưng Hà", "category": "environment", "approved_time": [2025, 12, 21, 22, 53, 5, 21078000]}	EVENT_APPROVED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
11	372b41ae-9f4e-4abe-b909-07c778f1f84f	42	2025-12-21 22:53:07.399587	f	{"name": "Ngày hội trồng cây xanh ven sông", "category": "environment", "approved_time": [2025, 12, 21, 22, 53, 7, 305980900]}	EVENT_APPROVED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
12	3c7fc337-528c-478a-8fb8-53cbbc266725	41	2025-12-21 23:01:40.356676	f	{"requested_at": [2025, 12, 21, 23, 1, 39, 658409000]}	USER_EVENT_REQUESTED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
13	41	41	2025-12-21 23:02:06.879059	f	{"reviewed_at": [2025, 12, 21, 23, 2, 6, 758963300]}	USER_EVENT_APPROVED	3c7fc337-528c-478a-8fb8-53cbbc266725
14	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	41	2025-12-21 23:02:49.375798	f	{"updated_fields": {"name": "Sự kiện nhặt rác ở Quảng Trường Hưng ", "address": "Quảng Trường Hùng Hà, , Tỉnh Bình Định", "capacity": 50, "category": "environment", "end_time": [2025, 12, 26, 21, 24], "start_time": [2025, 12, 25, 17, 24], "description": "Sự kiện nhặt rác tại Quảng Trường Hùng Hà được tổ chức nhằm nâng cao ý thức bảo vệ môi trường cho người dân địa phương và cộng đồng xung quanh. Chương trình quy tụ các tình nguyện viên, học sinh, sinh viên và các tổ chức xã hội cùng tham gia thu gom rác thải, phân loại rác và làm sạch khu vực công cộng. Ngoài hoạt động nhặt rác, sự kiện còn có các buổi tuyên truyền về giảm thiểu rác thải nhựa và bảo vệ cảnh quan đô thị.", "registration_deadline": [2025, 12, 23, 21, 24]}}	EVENT_UPDATED	3c7fc337-528c-478a-8fb8-53cbbc266725
8	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	43	2025-12-21 21:57:48.519807	t	{"name": "Chiến dịch làm sạch bãi biển mùa hè", "category": "environment", "end_time": [2025, 12, 22, 12, 56], "start_time": [2025, 12, 22, 9, 56]}	EVENT_REQUESTED	372b41ae-9f4e-4abe-b909-07c778f1f84f
15	3c7fc337-528c-478a-8fb8-53cbbc266725	42	2025-12-21 23:09:05.732432	f	{"requested_at": [2025, 12, 21, 23, 9, 5, 687159000]}	USER_EVENT_REQUESTED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
16	42	42	2025-12-21 23:12:42.639389	f	{"reviewed_at": [2025, 12, 21, 23, 12, 42, 602741200]}	USER_EVENT_APPROVED	3c7fc337-528c-478a-8fb8-53cbbc266725
17	79c944f2-ac6b-49fb-beb4-fc2d15d672f9	39	2025-12-21 23:39:22.431204	f	{"requested_at": [2025, 12, 21, 23, 39, 22, 159161000]}	USER_EVENT_REQUESTED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
18	39	39	2025-12-21 23:39:49.660526	f	{"reviewed_at": [2025, 12, 21, 23, 39, 49, 617321700]}	USER_EVENT_APPROVED	79c944f2-ac6b-49fb-beb4-fc2d15d672f9
19	3c7fc337-528c-478a-8fb8-53cbbc266725	40	2025-12-21 23:41:51.575291	f	{"requested_at": [2025, 12, 21, 23, 41, 51, 542718000]}	USER_EVENT_REQUESTED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
20	40	40	2025-12-21 23:42:05.775913	f	{"reviewed_at": [2025, 12, 21, 23, 42, 5, 744711900]}	USER_EVENT_APPROVED	3c7fc337-528c-478a-8fb8-53cbbc266725
21	3c7fc337-528c-478a-8fb8-53cbbc266725	25	2025-12-21 23:42:59.977365	f	{"content": "Hôm nay rất vui cảm ơn mọi người"}	POST_CREATED	3c7fc337-528c-478a-8fb8-53cbbc266725
22	3c7fc337-528c-478a-8fb8-53cbbc266725	25	2025-12-21 23:43:07.191151	f	{"content": "LOVE"}	REACTION	3c7fc337-528c-478a-8fb8-53cbbc266725
23	3c7fc337-528c-478a-8fb8-53cbbc266725	25	2025-12-21 23:43:21.224351	f	{"content": "Tuyệt lắm"}	COMMENT	3c7fc337-528c-478a-8fb8-53cbbc266725
25	3c7fc337-528c-478a-8fb8-53cbbc266725	25	2025-12-21 23:43:51.513271	t	{"content": "@Nguyen Hoang Viet Thật tuyệt"}	COMMENT	3c7fc337-528c-478a-8fb8-53cbbc266725
24	3c7fc337-528c-478a-8fb8-53cbbc266725	25	2025-12-21 23:43:39.846257	t	{"content": "tuyệt vời"}	COMMENT	3c7fc337-528c-478a-8fb8-53cbbc266725
26	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	44	2025-12-21 23:46:49.118464	f	{"name": "Dọn rác ở E3 xuân thủy", "category": "environment", "end_time": [2025, 12, 24, 23, 48], "start_time": [2025, 12, 23, 13, 46]}	EVENT_REQUESTED	372b41ae-9f4e-4abe-b909-07c778f1f84f
27	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	41	2025-12-21 23:47:07.179513	f	{"name": "Sự kiện nhặt rác ở Quảng Trường Hưng "}	EVENT_DELETED	3c7fc337-528c-478a-8fb8-53cbbc266725
28	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	42	2025-12-21 23:47:22.263739	f	{"updated_fields": {"name": "Ngày hội trồng cây xanh", "address": "Biển Lê Chân, , Thành phố Hải Phòng", "capacity": 20, "category": "environment", "end_time": [2025, 12, 26, 22, 26], "start_time": [2025, 12, 25, 9, 25], "description": "Ngày hội trồng cây xanh ven sông được tổ chức với mục tiêu cải thiện hệ sinh thái và chống xói mòn bờ sông.", "registration_deadline": [2025, 12, 22, 21, 26]}}	EVENT_UPDATED	3c7fc337-528c-478a-8fb8-53cbbc266725
29	114499670013675731357	42	2025-12-21 23:49:17.793359	f	{"requested_at": [2025, 12, 21, 23, 49, 17, 761428000]}	USER_EVENT_REQUESTED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
30	42	42	2025-12-21 23:50:09.934063	f	{"reviewed_at": [2025, 12, 21, 23, 50, 9, 902350000]}	USER_EVENT_APPROVED	114499670013675731357
31	42	42	2025-12-21 23:51:07.843387	f	{"completed_at": [2025, 12, 21, 23, 51, 7, 771510100]}	USER_EVENT_COMPLETED	114499670013675731357
32	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 23:52:22.900428	f	{"content": "TÔI RẤT MONG CHỜ NGÀY MAI"}	POST_CREATED	114499670013675731357
33	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	26	2025-12-21 23:52:37.101502	f	{"content": "HAHA"}	REACTION	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
34	372b41ae-9f4e-4abe-b909-07c778f1f84f	44	2025-12-21 23:54:57.837795	f	{"name": "Dọn rác ở E3 xuân thủy", "category": "environment", "approved_time": [2025, 12, 21, 23, 54, 57, 768724200]}	EVENT_APPROVED	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
\.


--
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.subscriptions (id, endpoint, auth, p256dh, user_id) FROM stdin;
\.


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.notification_id_seq', 34, true);


--
-- Name: subscriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.subscriptions_id_seq', 1, false);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: subscriptions ukljxkq0ssso4jkogtryl46go0w; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT ukljxkq0ssso4jkogtryl46go0w UNIQUE (endpoint);


--
-- Name: idx_notification_user_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_notification_user_id ON public.notification USING btree (user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict kdAzY8yCand9f9ROhpEAa8ohVQqUnJo7DEtCLxy80U8ipwusSjyEsNUkFAqy5M5

