--
-- PostgreSQL database dump
--

\restrict a1XBcuehanWqfoT1OsIuKOvLWrwsrgklkifby2hEQN7e2qZosVImeN5R7uuwhdY

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: event_snapshot; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.event_snapshot (
    event_id bigint NOT NULL,
    capacity integer NOT NULL,
    owner_id character varying(255) NOT NULL,
    status smallint NOT NULL,
    CONSTRAINT event_snapshot_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.event_snapshot OWNER TO admin;

--
-- Name: user_event; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_event (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    event_id bigint,
    note character varying(255),
    reviewed_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT user_event_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.user_event OWNER TO admin;

--
-- Name: user_event_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: event_snapshot; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.event_snapshot (event_id, capacity, owner_id, status) FROM stdin;
1	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
8	3000	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
7	3000	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
6	3000	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
9	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
10	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
11	20	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
12	20	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
13	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
14	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
15	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
16	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
17	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
18	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
19	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
20	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
22	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
21	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
24	47	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
25	20	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
26	10	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
34	40	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
36	200	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
37	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
38	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
39	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
40	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
43	50	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
42	20	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	1
\.


--
-- Data for Name: user_event; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_event (id, completed_at, created_at, event_id, note, reviewed_at, status, updated_at, user_id) FROM stdin;
12	\N	2025-12-06 14:00:27.660015	14	ok	2025-12-06 15:44:48.589728	REJECTED	2025-12-06 15:44:48.589728	9ef815af-e6ce-4405-b92e-f44ec2c9750c
48	2025-12-20 20:33:20.8764	2025-12-20 18:42:07.989985	36	Tuyệt vời	2025-12-20 19:15:11.930209	COMPLETED	2025-12-20 20:33:28.582283	3c7fc337-528c-478a-8fb8-53cbbc266725
14	2025-12-08 20:54:29.190175	2025-12-06 14:03:54.564082	14		2025-12-06 16:22:35.905519	COMPLETED	2025-12-08 20:54:29.190678	d134ffc1-4804-4bd0-b0b5-9e4e95b30cae
50	\N	2025-12-21 09:02:20.985987	39	\N	2025-12-21 09:02:52.130772	APPROVED	2025-12-21 09:02:52.78427	3c7fc337-528c-478a-8fb8-53cbbc266725
24	2025-12-08 20:54:30.633675	2025-12-06 21:49:49.239586	13		2025-12-07 13:00:51.623696	COMPLETED	2025-12-08 20:54:30.639699	ef87abed-f4ad-4647-8c95-e4f34f34dbba
25	2025-12-08 20:54:32.039122	2025-12-07 12:29:00.032255	17		2025-12-07 12:29:10.870418	COMPLETED	2025-12-08 20:54:32.039746	ef87abed-f4ad-4647-8c95-e4f34f34dbba
27	2025-12-08 20:54:33.350172	2025-12-07 13:32:10.445138	24		2025-12-07 13:37:20.415857	COMPLETED	2025-12-08 20:54:33.350702	ef87abed-f4ad-4647-8c95-e4f34f34dbba
29	2025-12-08 20:54:34.868682	2025-12-07 17:33:48.209775	25		2025-12-07 18:08:20.372799	COMPLETED	2025-12-08 20:54:34.869778	ef87abed-f4ad-4647-8c95-e4f34f34dbba
11	2025-12-08 20:54:37.892129	2025-12-06 13:59:57.826568	14		2025-12-06 15:44:41.203939	COMPLETED	2025-12-08 20:54:37.89379	3c7fc337-528c-478a-8fb8-53cbbc266725
36	2025-12-08 18:43:24.526176	2025-12-08 14:44:42.460051	26	OK	2025-12-08 14:45:01.625911	COMPLETED	2025-12-08 18:43:24.558667	ef87abed-f4ad-4647-8c95-e4f34f34dbba
31	2025-12-08 20:09:38.633093	2025-12-07 18:01:32.021857	25		2025-12-07 18:08:22.058637	COMPLETED	2025-12-08 20:09:38.672422	3c7fc337-528c-478a-8fb8-53cbbc266725
26	2025-12-08 20:09:41.670244	2025-12-07 12:34:33.966429	16		2025-12-07 12:34:43.874688	COMPLETED	2025-12-08 20:09:41.670244	ef87abed-f4ad-4647-8c95-e4f34f34dbba
32	2025-12-08 20:54:23.99484	2025-12-07 18:12:53.289936	26	OK	2025-12-08 14:43:21.50658	COMPLETED	2025-12-08 20:54:24.045084	3c7fc337-528c-478a-8fb8-53cbbc266725
41	\N	2025-12-08 21:14:37.303664	26	\N	2025-12-08 21:15:33.727656	APPROVED	2025-12-08 21:15:33.730787	5fc47331-6243-4997-b08b-d18af4420aa5
39	\N	2025-12-08 21:10:41.490254	26	\N	2025-12-08 21:15:55.870132	APPROVED	2025-12-08 21:15:55.871571	115404184867109357292
52	\N	2025-12-21 11:22:27.875873	34	\N	2025-12-21 14:23:05.088337	APPROVED	2025-12-21 14:23:05.234099	5fc47331-6243-4997-b08b-d18af4420aa5
53	\N	2025-12-21 11:34:40.071789	34	\N	2025-12-21 18:44:55.681329	APPROVED	2025-12-21 18:44:55.719528	3c7fc337-528c-478a-8fb8-53cbbc266725
54	\N	2025-12-21 20:49:29.294899	38	\N	2025-12-21 20:50:41.770275	APPROVED	2025-12-21 20:50:41.893944	3c7fc337-528c-478a-8fb8-53cbbc266725
42	2025-12-20 11:22:12.386509	2025-12-08 21:43:22.200243	26	ok	2025-12-08 22:04:59.69106	COMPLETED	2025-12-20 11:22:12.472298	5f666bb5-ef5b-4123-9c62-b6edc382105c
46	2025-12-11 09:31:27.159747	2025-12-11 01:56:49.941092	26	Tuyệt vời	2025-12-11 02:02:38.657591	COMPLETED	2025-12-20 12:22:13.756649	de4050ff-5c12-41a1-bc36-29c06c276ada
28	\N	2025-12-07 16:56:55.375556	15	\N	2025-12-20 16:41:29.131195	REJECTED	2025-12-20 16:41:29.179261	3c7fc337-528c-478a-8fb8-53cbbc266725
58	\N	2025-12-21 23:41:51.542718	40	\N	2025-12-21 23:42:05.744712	APPROVED	2025-12-21 23:42:05.747158	3c7fc337-528c-478a-8fb8-53cbbc266725
59	2025-12-21 23:51:07.77151	2025-12-21 23:49:17.761428	42	bạn làm rất tiyuee	2025-12-21 23:50:09.90235	COMPLETED	2025-12-21 23:51:19.253923	114499670013675731357
\.


--
-- Name: user_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_event_id_seq', 59, true);


--
-- Name: event_snapshot event_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.event_snapshot
    ADD CONSTRAINT event_snapshot_pkey PRIMARY KEY (event_id);


--
-- Name: user_event uk_user_event_user_id_event_id; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_event
    ADD CONSTRAINT uk_user_event_user_id_event_id UNIQUE (user_id, event_id);


--
-- Name: user_event user_event_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_event
    ADD CONSTRAINT user_event_pkey PRIMARY KEY (id);


--
-- Name: idx_user_event_event_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_user_event_event_id ON public.user_event USING btree (event_id);


--
-- Name: idx_user_event_user_id; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_user_event_user_id ON public.user_event USING btree (user_id);


--
-- Name: user_event fk3uvd3orx1d50sms469ialvyqd; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_event
    ADD CONSTRAINT fk3uvd3orx1d50sms469ialvyqd FOREIGN KEY (event_id) REFERENCES public.event_snapshot(event_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict a1XBcuehanWqfoT1OsIuKOvLWrwsrgklkifby2hEQN7e2qZosVImeN5R7uuwhdY

