apiVersion: v1
kind: ConfigMap
metadata:
  name: volunteerhub-config
data:
  PUBLIC_BASE_URL: "__PUBLIC_BASE_URL__"
  APP_CORS_ALLOWED_ORIGINS: "__PUBLIC_BASE_URL__"
  CLIENT_APP_URI: "__PUBLIC_BASE_URL__"
  REDIRECT_URI: "__PUBLIC_BASE_URL__/login/oauth2/code/volunteerhub"
  VOLUNTEER_HUB_AS_URI: "__PUBLIC_BASE_URL__"
  VOLUNTEER_HUB_AS_JWK_URI: "http://authorization-server:7070/oauth2/jwks"
