--
-- PostgreSQL database dump
--

\restrict bdaPXEz68Wxi3Ax6qMokQvvL1t3tRCDHlN1ry1uNUWTK9PNeKESOIQvQBKrXjIU

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.address (
    id bigint NOT NULL,
    district character varying(255) NOT NULL,
    province character varying(255) NOT NULL,
    street character varying(255) NOT NULL
);


ALTER TABLE public.address OWNER TO admin;

--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_badge; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_badge (
    id bigint NOT NULL,
    badge_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.user_badge OWNER TO admin;

--
-- Name: user_badge_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_badge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_badge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_login_history; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_login_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    ip_address character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.user_login_history OWNER TO admin;

--
-- Name: user_login_history_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_login_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_login_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    address_id bigint,
    auth_provider character varying(255) NOT NULL,
    avatar_url character varying(255),
    bio character varying(255),
    created_at timestamp(6) without time zone,
    date_of_birth date,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    is_dark_mode boolean DEFAULT false NOT NULL,
    phone_number character varying(15),
    role character varying(255) NOT NULL,
    skills jsonb,
    status character varying(255) NOT NULL,
    total_events integer NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'BANNED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO admin;

--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.address (id, district, province, street) FROM stdin;
4	Huyện Tây Sơn	Tỉnh Bình Định	S2.05, Vinhomes Smart City
5	Thành phố Yên Bái	Tỉnh Yên Bái	S2.05, Vinhomes Smart City
10	Huyện Lạng Giang	Tỉnh Bắc Giang	S2.05, Vinhomes Smart City
11	Huyện Đông Anh	Thành phố Hà Nội	S2.05, Vinhomes Smart City
12	Quận Cầu Giấy	Thành phố Hà Nội	THAI BINH PROVINCE
13	Huyện Gia Lâm	Thành phố Hà Nội	THAI BINH PROVINCE
\.


--
-- Data for Name: user_badge; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_badge (id, badge_id, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: user_login_history; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_login_history (id, created_at, ip_address, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (id, address_id, auth_provider, avatar_url, bio, created_at, date_of_birth, email, full_name, is_dark_mode, phone_number, role, skills, status, total_events, updated_at, username) FROM stdin;
114499670013675731357	13	local	https://lh3.googleusercontent.com/a/ACg8ocIZyClWilWkVtpNNqs1L8tQmhlwNWPEhf4Ow-Gy9Z1tswqX0w=s96-c		2025-12-03 23:53:27.888081	2025-12-09	nguphenoi@gmail.com	đoàn văn	f	0366482818	USER	\N	BANNED	0	2025-12-21 23:56:09.11871	nguphenoi@gmail.com
111233063192526846687	\N	local	https://lh3.googleusercontent.com/a/ACg8ocIjia_bNO3sUHQWPL2yLno6Xl8qzgHX85MQ5ZgC-0pJQFbfRg=s96-c		2025-12-03 23:53:48.167909	\N	23020170@vnu.edu.vn	23020170 Nguyễn Hoàng Việt	f	\N	USER	\N	ACTIVE	0	2025-12-03 23:53:48.168455	23020170@vnu.edu.vn
3e7d0df7-750a-4364-95e7-8bea038c4069	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=manager2005		2025-12-11 01:37:10.137342	\N	manager2005@gmail.com	imagee	f	\N	MANAGER	\N	ACTIVE	0	2025-12-11 01:37:10.228355	manager2005@gmail.com
a7b469ac-513f-4b0e-aa3a-601c809e0c58	4	local	https://api.dicebear.com/7.x/avataaars/svg?seed=q	sdafsddsfs	2025-12-04 00:00:25.066295	2020-03-18	q@asdjfkasdqewr	Nguyen Hoang Viet	f	0366482818	USER	["react"]	ACTIVE	0	2025-12-04 00:02:12.730619	q@asdjfkasdqewr
109974589078245626896	\N	local	https://lh3.googleusercontent.com/a/ACg8ocKZCoxchhVgWrWBGPD-yzAtY9Jm1MbOW_HM2Ok3hyKiOASGkA=s96-c		2025-12-04 13:46:07.874138	\N	vietthdn123@gmail.com	Hhj Viet	f	\N	USER	\N	ACTIVE	0	2025-12-04 13:46:07.874698	vietthdn123@gmail.com
a11746db-d6c2-4f0c-9233-110696190972	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=admin		2025-12-04 22:31:00.414272	\N	admin@gmsdil.com	vietthdn123	f	\N	USER	\N	ACTIVE	0	2025-12-04 22:31:00.414272	admin@gmsdil.com
372b41ae-9f4e-4abe-b909-07c778f1f84f	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=vietthdndsadsf2005		2025-12-04 22:31:59.730276	\N	vietthdndsadsf2005@gmail.com	vietthdn123	f	\N	ADMIN	\N	ACTIVE	0	2025-12-04 22:31:59.730802	vietthdndsadsf2005@gmail.com
ef87abed-f4ad-4647-8c95-e4f34f34dbba	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=dfasdf		2025-12-05 00:35:41.394883	\N	dfasdf@gmail.comsd	VBearCode	f	\N	USER	\N	ACTIVE	0	2025-12-05 00:35:41.394883	dfasdf@gmail.comsd
9ef815af-e6ce-4405-b92e-f44ec2c9750c	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=manager2d		2025-12-05 00:35:48.472704	\N	manager2d@gmajdkkf	VBearCode	f	\N	USER	\N	ACTIVE	0	2025-12-05 00:35:48.472704	manager2d@gmajdkkf
62e2c6de-aa4b-48b0-a593-d633e94dca83	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=mdsanager2d		2025-12-05 00:35:54.006251	\N	mdsanager2d@gmajdkkf	VBearCode	f	\N	USER	\N	ACTIVE	0	2025-12-05 00:35:54.051962	mdsanager2d@gmajdkkf
e535894c-26f7-43f9-81c4-de352490e520	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=managedsr2		2025-12-05 00:36:14.803736	\N	managedsr2@gnsdalfd	Nguyen Hoang Viet	f	\N	USER	\N	ACTIVE	0	2025-12-05 00:36:14.821782	managedsr2@gnsdalfd
4937d6df-4387-4358-8035-628e980fd4dd	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=quangtung		2025-12-05 00:36:48.097109	\N	quangtung@skjf	Nguyen Hoang Viet	f	\N	MANAGER	\N	ACTIVE	0	2025-12-05 00:36:48.114449	quangtung@skjf
b313283b-48cd-4a10-9478-8ab30fead822	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=manager2		2025-12-05 15:53:54.053397	\N	manager2@gnsdalf	Nguyen Hoang Viet	f	\N	USER	\N	ACTIVE	0	2025-12-05 15:53:54.053397	manager2@gnsdalf
de4050ff-5c12-41a1-bc36-29c06c276ada	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=admi		2025-12-06 00:15:18.479355	\N	admi@gmail.com	dfasdf	f	\N	USER	\N	ACTIVE	0	2025-12-06 00:15:18.479355	admi@gmail.com
a80588f6-acc0-47eb-8fbe-2f9bca5269c8	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=quangtung		2025-12-06 01:16:20.183275	\N	quangtung@skjfdsd	Nguyen Hoang Viet	f	\N	MANAGER	\N	ACTIVE	0	2025-12-06 01:16:20.183275	quangtung@skjfdsd
d134ffc1-4804-4bd0-b0b5-9e4e95b30cae	5	local	https://api.dicebear.com/7.x/avataaars/svg?seed=Vietthdn2005	bio	2025-12-04 22:06:17.899668	2025-12-05	Vietthdn2005@gmail.com	Nguyen Hoang Viet	f	0366482818	MANAGER	["react"]	ACTIVE	0	2025-12-07 00:01:14.358022	Vietthdn2005@gmail.com
102770268367938617290	\N	local	https://lh3.googleusercontent.com/a/ACg8ocILzDhfS0cYkoeSGc2KBEnqWiv6ZNUR_RgkTrHz123wjVnU0g=s96-c		2025-12-07 15:09:45.630308	\N	nguyenanh27081978@gmail.com	VIỆT NGUYÊN HOÀNG	f	\N	USER	\N	ACTIVE	0	2025-12-07 15:09:45.630308	nguyenanh27081978@gmail.com
115404184867109357292	\N	local	https://lh3.googleusercontent.com/a/ACg8ocIzZMB9s-6DBtH_kzw_jZce3T1GsbgNZLb0yjtQ9yUbeMtJZQ=s96-c		2025-12-08 21:10:14.855346	\N	vietthdn2010@gmail.com	Fhi Fhi	f	\N	USER	\N	ACTIVE	0	2025-12-08 21:10:14.856883	vietthdn2010@gmail.com
5f666bb5-ef5b-4123-9c62-b6edc382105c	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=123123123		2025-12-08 21:43:08.644437	\N	123123123@kjsdfnl	Nguyen Hoang Viet	f	\N	USER	\N	ACTIVE	0	2025-12-08 21:43:08.645063	123123123@kjsdfnl
7ee2c77a-b2ed-469d-9f42-6e8bb5df974a	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=vietthdn201		2025-12-09 00:21:19.826798	\N	vietthdn201@gmail.com	Nguyen Hoang Viet	f	\N	USER	\N	ACTIVE	0	2025-12-09 00:21:19.826798	vietthdn201@gmail.com
6f079306-e075-46c4-bbf7-66e9eac096e5	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=admin		2025-12-11 01:33:59.959537	\N	admin@gmail.com	viett	f	\N	USER	\N	ACTIVE	0	2025-12-11 01:33:59.959537	admin@gmail.com
3c7fc337-528c-478a-8fb8-53cbbc266725	10	local	https://api.dicebear.com/7.x/avataaars/svg?seed=vietthdn	gg	2025-12-04 13:30:47.268711	2012-03-28	vietthdn@shaskfjss	Nguyen Hoang Viet	f	0366482819	USER	["tuyệt"]	ACTIVE	0	2025-12-20 16:52:07.179357	vietthdn@shaskfjss
5fc47331-6243-4997-b08b-d18af4420aa5	11	local	https://api.dicebear.com/7.x/avataaars/svg?seed=Vietthdn200ddd5d		2025-12-08 21:14:08.936628	2012-02-16	Vietthdn200ddd5d@gmail.com	Nguyen Hoang Viet	f		USER	\N	ACTIVE	0	2025-12-21 11:21:28.656955	Vietthdn200ddd5d@gmail.com
686a4570-6a46-414d-a50f-5b5f19fce003	\N	local	https://api.dicebear.com/7.x/avataaars/svg?seed=manager68		2025-12-21 23:34:02.23872	\N	manager68@gmail.com	Luu Quang Tung	f	\N	USER	\N	ACTIVE	0	2025-12-21 23:34:02.23872	manager68@gmail.com
79c944f2-ac6b-49fb-beb4-fc2d15d672f9	12	local	https://api.dicebear.com/7.x/avataaars/svg?seed=volunteer20005		2025-12-21 23:36:37.701685	2007-02-14	volunteer20005@gmail.com	Luu Quang Tung	f	0366482818	USER	\N	ACTIVE	0	2025-12-21 23:37:39.946848	volunteer20005@gmail.com
\.


--
-- Name: address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.address_id_seq', 13, true);


--
-- Name: user_badge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_badge_id_seq', 1, false);


--
-- Name: user_login_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_login_history_id_seq', 1, false);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);


--
-- Name: address ukjwxme4q0mrlmyw8rkrpe8j4gw; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT ukjwxme4q0mrlmyw8rkrpe8j4gw UNIQUE (province, district, street);


--
-- Name: user_badge user_badge_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_badge
    ADD CONSTRAINT user_badge_pkey PRIMARY KEY (id);


--
-- Name: user_login_history user_login_history_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_login_history
    ADD CONSTRAINT user_login_history_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_badge fka96xbjeyiemypugmi9g8x8fiu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_badge
    ADD CONSTRAINT fka96xbjeyiemypugmi9g8x8fiu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users fkditu6lr4ek16tkxtdsne0gxib; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkditu6lr4ek16tkxtdsne0gxib FOREIGN KEY (address_id) REFERENCES public.address(id);


--
-- Name: user_login_history fkthvsfa8x1rhm6fbi1ysbsnsac; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_login_history
    ADD CONSTRAINT fkthvsfa8x1rhm6fbi1ysbsnsac FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict bdaPXEz68Wxi3Ax6qMokQvvL1t3tRCDHlN1ry1uNUWTK9PNeKESOIQvQBKrXjIU

