grafana:
  service:
    type: NodePort
    nodePort: 30300
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: observability
      folder: VolunteerHub
  additionalDataSources:
    - name: Loki
      uid: Loki
      type: loki
      access: proxy
      url: http://loki.observability.svc.cluster.local:3100
    - name: Tempo
      uid: Tempo
      type: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki
        serviceMap:
          datasourceUid: Prometheus

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: false
